stages:
  - lint
  - jest
  - audit
  - deploy

lint:
  stage: lint
  image: node:14
  script:
    - npm install
    - npm run lint

jest:
  stage: jest
  image: node:14
  script:
    - npm install
    - npm run test

audit:
  stage: audit
  image: node:14
  script:
    - npm install
    - npm audit

deploy:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/expresscrypto.git
    - git push -f heroku master