stages:
  - build
  - lint

build:
  stage: build
  image: node:14
  script:
    - npm install
  cache:
    paths:
      - ./node_modules
  only:
    - develop

lint:
  stage: lint
  image: node:14
  script:
    - npm run lint
  cache:
    paths:
      - ./node_modules
  only:
    - develop