stages:
  - lint
  - jest
  - audit
  - deploy

lint:
  stage: lint
  image: node:14
  script:
    - npm install
    - npm run lint

jest:
  stage: jest
  image: node:14
  script:
    - npm install
    - npm run test

audit:
  stage: audit
  image: node:14
  script:
    - npm install
    - npm audit

deploy:
  stage: deploy
  image: ruby:2.7
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY --skip_cleanup=true