stages:
  - build
  - lint
  - deploy

build:
  stage: build
  image: node:14
  script:
    - npm install
  cache:
    paths:
      - ./node_modules
  only:
    - develop

lint:
  stage: lint
  image: node:14
  script:
    - npm run lint
  cache:
    paths:
      - ./node_modules
  only:
    - develop

deploy:
  stage: deploy
  image: ruby:2.7
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY --skip_cleanup=true
  only:
    - develop