before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
#  - lint
#  - jest
#  - audit
  - deploy

#lint:
#  stage: lint
#  image: node:14
#  script:
#    - npm install
#    - npm run lint
#
#jest:
#  stage: jest
#  image: node:14
#  script:
#    - npm install
#    - npm run test
#
#audit:
#  stage: audit
#  image: node:14
#  script:
#    - npm install
#    - npm audit

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=expresscrypto --api-key=4122e720-9739-4b60-afc8-98159a05cb4a
  only:
    - develop